"""add_all_bmis_tables

Revision ID: 484ede310ce9
Revises: 5d69f4c333e3
Create Date: 2026-05-08 05:38:49.351287+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484ede310ce9'
down_revision: Union[str, None] = '5d69f4c333e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='announcementstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.Enum('ALL', 'RESIDENTS', 'SENIORS', 'YOUTH', 'BUSINESSES', name='targetaudience'), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('certificate_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_type', sa.Enum('BARANGAY_CLEARANCE', 'INDIGENCY', 'RESIDENCY', 'BUSINESS_CLEARANCE', 'GOOD_MORAL', name='certificatetype'), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_type')
    )
    op.create_table('emergency_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('FIRE', 'FLOOD', 'MEDICAL', 'CRIME', 'EARTHQUAKE', 'ACCIDENT', 'OTHER', name='emergencytype'), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'RESPONDING', 'RESOLVED', name='emergencystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_index(op.f('ix_emergency_alerts_id'), 'emergency_alerts', ['id'], unique=False)
    op.create_table('emergency_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('incident_type', sa.Enum('FIRE', 'FLOOD', 'MEDICAL', 'CRIME', 'EARTHQUAKE', 'ACCIDENT', 'OTHER', name='emergencytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('media_file', sa.String(length=255), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'RESPONDING', 'RESOLVED', name='emergencystatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_reports_id'), 'emergency_reports', ['id'], unique=False)
    op.create_table('blotter_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_number', sa.String(length=20), nullable=False),
    sa.Column('filed_by_id', sa.UUID(), nullable=True),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('complainant_contact', sa.String(length=50), nullable=True),
    sa.Column('complainant_email', sa.String(length=254), nullable=True),
    sa.Column('complainant_address', sa.Text(), nullable=True),
    sa.Column('respondent_name', sa.String(length=255), nullable=True),
    sa.Column('respondent_address', sa.Text(), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('incident_location', sa.String(length=255), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('FILED', 'UNDER_INVESTIGATION', 'MEDIATED', 'RESOLVED', 'DISMISSED', name='blotterstatus'), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blotter_reports_id'), 'blotter_reports', ['id'], unique=False)
    op.create_index(op.f('ix_blotter_reports_report_number'), 'blotter_reports', ['report_number'], unique=True)
    op.create_table('business_permits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('permit_number', sa.String(length=20), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_address', sa.Text(), nullable=False),
    sa.Column('house_num', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('is_renewal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', name='permitstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_number')
    )
    op.create_index(op.f('ix_business_permits_id'), 'business_permits', ['id'], unique=False)
    op.create_table('certificate_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('certificate_type', sa.Enum('BARANGAY_CLEARANCE', 'INDIGENCY', 'RESIDENCY', 'BUSINESS_CLEARANCE', 'GOOD_MORAL', name='certificatetype'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('complete_address', sa.Text(), nullable=False),
    sa.Column('house_num', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=254), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('agree_terms', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'RELEASED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_requests_id'), 'certificate_requests', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_request_number'), 'certificate_requests', ['request_number'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_reply', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=150), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email_address', sa.String(length=254), nullable=False),
    sa.Column('type', sa.Enum('NOISE', 'GARBAGE', 'PROPERTY', 'PUBLIC_DISTURBANCE', 'ILLEGAL_STRUCTURE', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('respondent_name', sa.String(length=150), nullable=True),
    sa.Column('respondent_address', sa.Text(), nullable=True),
    sa.Column('date_filed', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED', name='complaintstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaintpriority'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_reference_number'), 'complaints', ['reference_number'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('house_num', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('civil_status', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_complaints_reference_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_certificate_requests_request_number'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_id'), table_name='certificate_requests')
    op.drop_table('certificate_requests')
    op.drop_index(op.f('ix_business_permits_id'), table_name='business_permits')
    op.drop_table('business_permits')
    op.drop_index(op.f('ix_blotter_reports_report_number'), table_name='blotter_reports')
    op.drop_index(op.f('ix_blotter_reports_id'), table_name='blotter_reports')
    op.drop_table('blotter_reports')
    op.drop_index(op.f('ix_emergency_reports_id'), table_name='emergency_reports')
    op.drop_table('emergency_reports')
    op.drop_index(op.f('ix_emergency_alerts_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    op.drop_table('certificate_counters')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
