"""restructure_to_modules

Revision ID: f8d1f89fac3f
Revises: 484ede310ce9
Create Date: 2026-05-08 05:46:21.797809+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d1f89fac3f'
down_revision: Union[str, None] = '484ede310ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_alerts', sa.Column('status', sa.Enum('SUBMITTED', 'ACKNOWLEDGED', 'RESPONDING', 'RESOLVED', name='emergencystatus'), nullable=False))
    op.drop_column('emergency_alerts', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_alerts', sa.Column('is_active', postgresql.ENUM('SUBMITTED', 'ACKNOWLEDGED', 'RESPONDING', 'RESOLVED', name='emergencystatus'), autoincrement=False, nullable=False))
    op.drop_column('emergency_alerts', 'status')
    # ### end Alembic commands ###
